php 5.6-fpm-dev coposer added

diff --git a/5.6-fpm-dev/Dockerfile b/5.6-fpm-dev/Dockerfile
--- a/5.6-fpm-dev/Dockerfile
+++ b/5.6-fpm-dev/Dockerfile
@@ -67,6 +67,7 @@ RUN BEFORE_PWD=$(pwd) \
    && rm -r /opt/xdebug
 
 COPY extensions/ioncube_loader_lin_5.6.so /usr/local/lib/php/extensions/no-debug-non-zts-20131226/ioncube_loader_lin_5.6.so
+
 RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" \ 
    && echo "\nopcache.enable = On" >> /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini \
    && echo "zend_extension = xdebug.so" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
@@ -74,3 +75,24 @@ RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" \
    && echo "xdebug.idekey = PHPSTORM" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && sed -i '1s;^;zend_extension = ioncube_loader_lin_5.6.so\n;' "$PHP_INI_DIR/php.ini" \
    && sed -i 's;^memory_limit.*$;memory_limit = 512M\n;' "$PHP_INI_DIR/php.ini"
+
+ENV COMPOSER_ALLOW_SUPERUSER 1
+ENV COMPOSER_HOME /tmp
+ENV COMPOSER_VERSION 2.0.8
+
+RUN set -eux; \
+  curl --silent --fail --location --retry 3 --output /tmp/installer.php --url https://raw.githubusercontent.com/composer/getcomposer.org/cb19f2aa3aeaa2006c0cd69a7ef011eb31463067/web/installer; \
+  php -r " \
+    \$signature = '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5'; \
+    \$hash = hash('sha384', file_get_contents('/tmp/installer.php')); \
+    if (!hash_equals(\$signature, \$hash)) { \
+      unlink('/tmp/installer.php'); \
+      echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL; \
+      exit(1); \
+    }"; \
+  php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}; \
+  composer --ansi --version --no-interaction; \
+  rm -f /tmp/installer.php; \
+  find /tmp -type d -exec chmod -v 1777 {} +
+
+WORKDIR /app
